apiVersion: v1
kind: PersistentVolumClaim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  storageClassName: default
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
